### ISSUE TITLE
uses 

### ISSUE THREAD

**Issue by rockharshitmaurya** [joshcai/leetcode-sync#12]
can you provide me demo video that how to use , I am trying but not able to use

**Comment by rockharshitmaurya** [comment]
It's working now , but there is problem it does not sync my all the submission but only till last year it can sync

**Comment by joshcai** [comment]
Hi Harshit, hmm if it hasn't synced recent problems, it may be due to API throttling limits - usually just re-running the action later would pick up where it left off. 

I'm not sure if that's the case for your repo though - happy to take a look if you provide some more info (e.g. repository you are using / examples of problems that aren't synced).
