### ISSUE TITLE
Request failed with Status code 401

### ISSUE THREAD

**Issue by aviraltandon21** [joshcai/leetcode-sync#16]
Hi Josh!
I have been using Leetcode-sync for past month. And it's great.
From few days , my jobs have been failing, I thought maybe it was because my Leetcode csrf token had expired.
But when I update the token today and re run the job , it's failing again.
I am attaching the screenshot of the error I am encountering.
Can you please take a look.
![failing](https://user-images.githubusercontent.com/61861921/158068639-b47acfb2-1333-4fb4-a902-98166b7e5908.jpg)

Thanks and regards

**Comment by joshcai** [comment]
Hi @aviraltandon21, hmm could you describe how you updated the token? It does look to be the same error as https://github.com/joshcai/leetcode-sync/issues/7 which is also caused by csrf token expiring. You could also try the chrome extension mentioned here: https://github.com/joshcai/leetcode-sync/issues/7#issuecomment-779557829 which should make it easier to update the variables.

**Comment by aviraltandon21** [comment]
Hi @joshcai ,
I installed the chrome extension and linked it with my repo. But when I am trying to sync ,it is giving me the following error
![workflow_dispatch](https://user-images.githubusercontent.com/61861921/158122954-63682ead-b1cf-4cbc-aded-05da3f14eaca.jpg)

**Comment by aviraltandon21** [comment]
SORRY !
My mistake 
I enabled the workflow and its running now.
Thankyou so much for your help !

**Comment by chienhsiang-hung** [comment]
I had the same issue for quite a few weeks till I found this post and updated the token. lol
